"""
    Butler REST API Documentation

           Welcome to Butler API Documentation and Explorer       Butler API is built on and conforms to Open API 3.0 spec.       This enables you to automatically generate language specific clients for       languages/frameworks listed here: https://openapi-generator.tech/docs/generators/#client-generators         # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


import unittest

import butler
from butler.api.models_api import ModelsApi  # noqa: E501


class TestModelsApi(unittest.TestCase):
    """ModelsApi unit test stubs"""

    def setUp(self):
        self.api = ModelsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_custom_model(self):
        """Test case for create_custom_model

        """
        pass

    def test_get_document_enhanced_results(self):
        """Test case for get_document_enhanced_results

        """
        pass

    def test_get_model(self):
        """Test case for get_model

        """
        pass

    def test_get_training_document(self):
        """Test case for get_training_document

        """
        pass

    def test_get_training_documents(self):
        """Test case for get_training_documents

        """
        pass

    def test_train_custom_model(self):
        """Test case for train_custom_model

        Train a model  # noqa: E501
        """
        pass

    def test_update_document_labels(self):
        """Test case for update_document_labels

        Update labels for a specific document  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
