"""
    Butler REST API Documentation

           Welcome to Butler API Documentation and Explorer       Butler API is built on and conforms to Open API 3.0 spec.       This enables you to automatically generate language specific clients for       languages/frameworks listed here: https://openapi-generator.tech/docs/generators/#client-generators         # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import butler
from butler.model.model_training_document_status import ModelTrainingDocumentStatus
globals()['ModelTrainingDocumentStatus'] = ModelTrainingDocumentStatus
from butler.model.training_document_summary_dto import TrainingDocumentSummaryDto


class TestTrainingDocumentSummaryDto(unittest.TestCase):
    """TrainingDocumentSummaryDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTrainingDocumentSummaryDto(self):
        """Test TrainingDocumentSummaryDto"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TrainingDocumentSummaryDto()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
