"""
    Butler REST API Documentation

           Welcome to Butler API Documentation and Explorer       Butler API is built on and conforms to Open API 3.0 spec.       This enables you to automatically generate language specific clients for       languages/frameworks listed here: https://openapi-generator.tech/docs/generators/#client-generators         # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import butler
from butler.model.base_model_type import BaseModelType
from butler.model.model_field_dto import ModelFieldDto
from butler.model.model_status import ModelStatus
from butler.model.model_table_dto import ModelTableDto
from butler.model.submit_training_documents_disabled_reason import SubmitTrainingDocumentsDisabledReason
from butler.model.training_disabled_reason import TrainingDisabledReason
globals()['BaseModelType'] = BaseModelType
globals()['ModelFieldDto'] = ModelFieldDto
globals()['ModelStatus'] = ModelStatus
globals()['ModelTableDto'] = ModelTableDto
globals()['SubmitTrainingDocumentsDisabledReason'] = SubmitTrainingDocumentsDisabledReason
globals()['TrainingDisabledReason'] = TrainingDisabledReason
from butler.model.model_info_dto import ModelInfoDto


class TestModelInfoDto(unittest.TestCase):
    """ModelInfoDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testModelInfoDto(self):
        """Test ModelInfoDto"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ModelInfoDto()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
