"""
    Butler REST API Documentation

           Welcome to Butler API Documentation and Explorer       Butler API is built on and conforms to Open API 3.0 spec.       This enables you to automatically generate language specific clients for       languages/frameworks listed here: https://openapi-generator.tech/docs/generators/#client-generators         # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import butler
from butler.model.block_type import BlockType
globals()['BlockType'] = BlockType
from butler.model.block_dto import BlockDto


class TestBlockDto(unittest.TestCase):
    """BlockDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBlockDto(self):
        """Test BlockDto"""
        # FIXME: construct object with mandatory attributes with example values
        # model = BlockDto()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
