"""
    Butler REST API Documentation

           Welcome to Butler API Documentation and Explorer       Butler API is built on and conforms to Open API 3.0 spec.       This enables you to automatically generate language specific clients for       languages/frameworks listed here: https://openapi-generator.tech/docs/generators/#client-generators         # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


import unittest

import butler
from butler.api.queues_api import QueuesApi  # noqa: E501


class TestQueuesApi(unittest.TestCase):
    """QueuesApi unit test stubs"""

    def setUp(self):
        self.api = QueuesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_extraction_results(self):
        """Test case for get_extraction_results

        Get paginated list of extraction results for documents matching the query params  # noqa: E501
        """
        pass

    def test_upload_documents_to_queue(self):
        """Test case for upload_documents_to_queue

        Upload documents to the queue specified by <queueId> for processing  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
