"""
    Butler REST API Documentation

           Welcome to Butler API Documentation and Explorer       Butler API is built on and conforms to Open API 3.0 spec.       This enables you to automatically generate language specific clients for       languages/frameworks listed here: https://openapi-generator.tech/docs/generators/#client-generators         # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import butler
from butler.model.signature_field_labeled_result_dto import SignatureFieldLabeledResultDto
from butler.model.simple_field_labeled_result_dto import SimpleFieldLabeledResultDto
from butler.model.training_table_labeled_result_dto import TrainingTableLabeledResultDto
globals()['SignatureFieldLabeledResultDto'] = SignatureFieldLabeledResultDto
globals()['SimpleFieldLabeledResultDto'] = SimpleFieldLabeledResultDto
globals()['TrainingTableLabeledResultDto'] = TrainingTableLabeledResultDto
from butler.model.training_annotation_dto import TrainingAnnotationDto


class TestTrainingAnnotationDto(unittest.TestCase):
    """TrainingAnnotationDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTrainingAnnotationDto(self):
        """Test TrainingAnnotationDto"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TrainingAnnotationDto()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
