"""
    Butler REST API Documentation

           Welcome to Butler API Documentation and Explorer       Butler API is built on and conforms to Open API 3.0 spec.       This enables you to automatically generate language specific clients for       languages/frameworks listed here: https://openapi-generator.tech/docs/generators/#client-generators         # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import butler
from butler.model.signature_field_with_confidence_labeled_result_dto import SignatureFieldWithConfidenceLabeledResultDto
from butler.model.simple_field_with_confidence_labeled_result_dto import SimpleFieldWithConfidenceLabeledResultDto
from butler.model.training_table_with_confidence_labeled_result_dto import TrainingTableWithConfidenceLabeledResultDto
globals()['SignatureFieldWithConfidenceLabeledResultDto'] = SignatureFieldWithConfidenceLabeledResultDto
globals()['SimpleFieldWithConfidenceLabeledResultDto'] = SimpleFieldWithConfidenceLabeledResultDto
globals()['TrainingTableWithConfidenceLabeledResultDto'] = TrainingTableWithConfidenceLabeledResultDto
from butler.model.put_document_labels_dto import PutDocumentLabelsDto


class TestPutDocumentLabelsDto(unittest.TestCase):
    """PutDocumentLabelsDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPutDocumentLabelsDto(self):
        """Test PutDocumentLabelsDto"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PutDocumentLabelsDto()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
