"""
    Butler REST API Documentation

           Welcome to Butler API Documentation and Explorer       Butler API is built on and conforms to Open API 3.0 spec.       This enables you to automatically generate language specific clients for       languages/frameworks listed here: https://openapi-generator.tech/docs/generators/#client-generators         # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import butler
from butler.model.doc_ex_confidence import DocExConfidence
from butler.model.extracted_table_row_dto import ExtractedTableRowDto
globals()['DocExConfidence'] = DocExConfidence
globals()['ExtractedTableRowDto'] = ExtractedTableRowDto
from butler.model.extracted_table_dto import ExtractedTableDto


class TestExtractedTableDto(unittest.TestCase):
    """ExtractedTableDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testExtractedTableDto(self):
        """Test ExtractedTableDto"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ExtractedTableDto()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
